server:
  port: 8011
  
spring:
  application:
    name: master-data-service
  datasource:
    url: jdbc:mysql://localhost:3306/myspace
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect